### PR TITLE
feat: bring back the splash ✨

### PR DESCRIPTION
**Pull request by olizilla**
- Port the home page from https://github.com/ipld/website
- Update navbar to just have a link to `Documentation` & `Github` (this repo)
- Reinstate the Makefile, as requested
- Fetch the right hyperlink binary when on mac
- Make room for the root index.html by merging the docs intro with the welcome
- Move `/static/{img|css|js}` to `/{img|css|js}` move fewer things and include fewer characters
- Add the package-lock.json. Use node>=16 (and the npm>=7 that implies) for a good time. Older versions will be a bad time. Sorry. I don't make the rules. (npm changed it's lockfile format in npm@7. Just update your node install and never look back.

builds on the fine work of @rvagg in #97

| new (old) homepage |  docs home |
|----------------------|-------------|
| Screenshot 2021-06-20 at 21 55 08 |  Screenshot 2021-06-20 at 21 55 14 |

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by rvagg** [comment]
🧙 

_grumble grumble_ Makefile _grumble grumble_ package-lock.json _grumble grumble_

but lovely work! This rebases cleanly against `ipld/rvagg/package.json` which I rebased against `master` here late last week so you probably got the earlier, pre-rebased version of my branch, sorry! I've done a local rebase and tried it out and it works as advertised and has the pretty splash.

It'd be nice to get some theme work done on the actual docs, but incremental is good.

**Review by rvagg — APPROVED** [review]
needs a rebase to my branch and a double merge to get into master, but 👍

**Comment by olizilla** [comment]
i kno i kno, but @warpfork asked so nicely for the Makefile. The package-lock is a good idea tho and I will wrestle you for it.

Agree on the formatting of the docs too. We will iterate to victory on that in future PRs

**Comment by rvagg** [comment]
the thing that would make the package-lock.json reasonable for me is dependabot in this repo checking it regularly.

**Comment by rvagg** [comment]
^ that wasn't intended as a blocker, I don't care that much, I just have a thing about the overuse of package-lock.json files in general in the wrong places .. this isn't necessarily the wrong place.

**Comment by olizilla** [comment]
I'm in favour of the package-lock.json; once the spotlight moves on and this project sits idle for a year, i want it to still be buildable, and I always want CI to use the same deps as I do locally.  I'm not worried as much about security issues and silently adopting upstream bug fixes in this case as it's is a static website builder. I haven't yet got comfortable with the noise to utility ratio of dependabot. I would gladly burn the package-lock if that were the price of entry here.

**Comment by warpfork** [comment]
I ran with this in https://github.com/ipld/ipld/pull/106 .  Different commit hashes, same content.  It's merged -- so I'm gonna close this one.

**Comment by warpfork** [comment]
@olizilla , you're a hero for pulling this together.  Thank you.

**Pull request closed without merging**
